config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :books
  resources :authors

  

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors = Author.all
    end
    
    def show
        @author = Author.find(params[:id])
    end    
    
    def new
    end
    
    def create
        @author = Author.new(author_params)
        @author.save
        redirect_to @author
    end
    
    private
        def author_params
            params.require(:author).permit(:name, :bio)
        end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<h1>Listing authors</h1>
 
<table class="books_table">
  <tr>
    <th>Name</th>
  </tr>
 
  <% @authors.each do |author| %>
  <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
    <tr>
      <td><%= link_to author_path(author) do %><%=author.name %><% end %></td>
    </tr>
  <% end %>
</table>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_for :author, url: authors_path, html: {class: "new_sc_form"} do |f| %>

   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
   </p>
 
  <p>
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/authors/show.html.erb
<div class="scShow">
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @author.bio %>
</p>
</div>