config/routes.rb
Rails.application.routes.draw do

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :books
  resources :authors

  

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :author
    
    # http://www.korenlc.com/creating-a-simple-search-in-rails-4/
    def self.search(search)
        where("title LIKE ?", "%#{search}%")
        where("description LIKE ?", "%#{search}%")
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
        
        # http://www.korenlc.com/creating-a-simple-search-in-rails-4/
        if params[:search]
            @books = Book.search(params[:search])
        else
            @books = Book.all
        end
    end
    
    def show
        @book = Book.find(params[:id])
    end    
    
    def new
    end
    
    def create
        @book = Book.new(book_params)
        @book.save
        redirect_to @book
    end
    
    private
        def book_params
            params.require(:book).permit(:title, :author_id, :description, :price, :format, :availability)
        end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h1>Listing books</h1>

<!-- http://www.korenlc.com/creating-a-simple-search-in-rails-4/ -->
<% if @books.present? %>
<table class="books_table">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Price</th>
    <th>Format</th>
    <th>Availability</th>
  </tr>
 
  <% @books.each do |book| %>
    <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
    <tr>
      <td><%= link_to book_path(book) do %><%= book.title %><% end %></td>
      <td><%= link_to author_path(book.author) do %><%=book.author.name %><% end %></td>
      <td><%= number_to_currency book.price %></td>
      <td><%= book.format %></td>
      <td><%= book.availability %></td>
    </tr>
  <% end %>
</table>
<% else %>
  <p>There are no books containing the term(s) <%= params[:search] %>.</p>
<% end %>

<!-- http://www.korenlc.com/creating-a-simple-search-in-rails-4/ -->
<%= form_tag(books_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Books" %>
<%= submit_tag "Search" %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_for :book, url: books_path, html: {class: "new_sc_form"} do |f| %>

   <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
   </p>
   
    <p>
    <%= f.label :author %><br>
    <%= f.select :author_id, options_for_select(Author.all.map{|s|[s.name, s.id]}) %>
    </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
   <p>
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </p>
  
   <p>
    <%= f.label :availability %><br>
    <%= f.text_field :availability %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/show.html.erb
<div class="scShow">
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency @book.price %>
</p>
 
<p>
  <strong>Format:</strong>
  <%= @book.format %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @book.availability %>
</p>
</div>